name: Deploy Maintenance Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via rsync to /var/www/maintenance
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          echo "🔁 Deployment nach: /var/www/maintenance"

          rsync -avzr --delete \
            -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" \
            ./maintenance-page/ \
            $SSH_USER@$SSH_HOST:/var/www/maintenance

          rm -f deploy_key.pem
        env:
          SSH_KEY: ${{ secrets.TESTSERVER_SSH_KEY }}
          SSH_USER: ${{ secrets.TESTSERVER_USER }}
          SSH_HOST: ${{ secrets.TESTSERVER_HOST }}
