name: Deploy Static Files to Testserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy repository content via rsync
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          REPO_NAME="${{ github.event.repository.name }}"
          TARGET_PATH="/var/www/$REPO_NAME"

          echo "🔁 Deployment nach: $TARGET_PATH"

          # Sync gesamter Repo-Inhalt (ohne .git)
          rsync -avzr --delete --exclude=".git" -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./ $SSH_USER@$SSH_HOST:$TARGET_PATH

          # Führe remote das Setup-Skript aus
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "bash /opt/setup-preview-site.sh $REPO_NAME"

          rm -f deploy_key.pem
        env:
          SSH_KEY: ${{ secrets.TESTSERVER_SSH_KEY }}
          SSH_USER: ${{ secrets.TESTSERVER_USER }}
          SSH_HOST: ${{ secrets.TESTSERVER_HOST }}
